export const SET_YOUR_HAIR_STYLES = "SET_YOUR_HAIR_STYLES";

export const SET_HAIR_STYLE_BANK = "SET_HAIR_STYLE_BANK";

export const CHANGE_YOUR_HAIR_STYLES_ITEM = "CHANGE_YOUR_HAIR_STYLES_ITEM";

export const CHANGE_HAIR_STYLE_BANK_ITEM = "CHANGE_HAIR_STYLE_BANK_ITEM";

export const DELETE_HAIR_STYLE_BANK_ITEM = "DELETE_HAIR_STYLE_BANK_ITEM";
